[package]
name = "DungeonGame"
version = "0.1.0"
edition = "2021"
authors = ["Stoiman"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.32.1"
default-features = false
features = ["image"]
